### ISSUE TITLE
SyntaxWarning with Python3.8

### ISSUE THREAD

**Issue by iamaziz** [jrnl-org/jrnl#922] opened 2020-04-22 06:09 UTC
See below:

```
/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/time.py:60: SyntaxWarning: "is" with a literal. Did you mean "=="?
```

**Comment by tjstub** [comment] 2020-04-23 05:50
Randomly jumping in, but it looks like it was fixed [here](https://github.com/jrnl-org/jrnl/commit/59624a49419b5f7880547bb1ac2d9ddb34f97768#diff-364aeefa827f15278f254308500037e8)

Updating should fix your issue!

**Comment by wren** [comment] 2020-04-23 22:28
Closing as dupe of #878.

@tjstub Thanks for jumping in! We always appreciate community members' help. :)

@iamaziz The fix for this is in v2.4-beta, which is out right now. No new bugs for that build have been reported, so if this keeps up, it'll be released officially as v2.4 on Saturday.

**Closed by wren** 2020-04-23 22:28 UTC
Labels: duplicate

**Comment by iamaziz** [comment] 2020-04-24 00:15
Thanks
