### ISSUE TITLE
Wrong export to folder for records with non-ascii titles

### ISSUE THREAD

**Issue by murrrf** [jrnl-org/jrnl#580] opened 2019-03-12 15:30 UTC
My journal is filled in Cyrillic. Everything works fine until I want to export it as separate entries in a folder. When exporting an journal to a separate files an entry gets the file name consisting of the date of creation of the entry and its title. However, non-ASCII characters are converted to ASCII or discarded. In this case, entries created on the same day, but at different times, receive the same file name and for all the entries for a certain day, only the last one is saved. All other entries for the day are overwritten by the last file.

The steps to reproduce the problem. I created an empty journal, filled it out and then exported it.
```
$ jrnl -v
jrnl version 1.9.8
```
```
$ jrnl yesterday at 11:00: Первая запись. First record.
$ jrnl yesterday at 12:00: Вторая запись. Second record.
$ jrnl yesterday at 13:00: Третья запись. Third record.
$ jrnl today at 12:00: Tést chars çöüéæ. Fourth record. Non-ASCII symbols: çöüéæ.
$ jrnl --export md -o .
```
Actual result:
```
$ ls -l
-rw-rw-r-- 1 sergej sergej 68 Mar 12 17:42 2019-03-11_b.md
-rw-rw-r-- 1 sergej sergej 81 мар 12 17:42 2019-03-12_btest-chars-coue.md
```
```
$ cat *

### 2019-03-11 13:00, Третья запись. 

Third record.

 
### 2019-03-12 12:00, Tést chars çöüéæ. 

Fourth record. Non-ASCII symbols: çöüéæ.
 
```
As you see, first and second records are missing.

If the log is exported to a single file, then everything works as expected.
```
$ jrnl --export md -o jrnl.txt
$ cat jrnl.txt
```
Result:
```
2019
====

March
-----

### 2019-03-11 11:00, Первая запись. 

First record.

 

### 2019-03-11 12:00, Вторая запись. 

Second record.

 

### 2019-03-11 13:00, Третья запись. 

Third record.

 

### 2019-03-12 12:00, Tést chars çöüéæ. 

Fourth record. Non-ASCII symbols: çöüéæ.
```
It would be best if the file name included non-ASCII characters. Or at least the file name included not only the date, but also the time the record was created.

**Comment by wren** [comment] 2019-04-20 19:09
This appears to be related to the handling of file names. From the test above, it looks like the first three entries are being written to the same file (one at a time, so that each one overwrites the previous one). That's why only two entries are there at the end. I tested this with a few more entries in Cyrillic, and it's always the latest entry that remains (all earlier ones are overwritten). 

I haven't had a chance to look into it deeper yet, but I'm guessing that this related to the part of the code that formats the file name for the export.

Incidentally, this also seems to point at a separate bug where, if you have multiple entries on the same day with the same title, they will also overwrite each other (since the export file name format is `yyyy-mm-dd_title-goes-here`).

**Comment by murrrf** [comment] 2019-07-09 09:34
I think this issue is still relevant.

**Comment by wren** [comment] 2019-08-09 15:20
Agreed. Still relevant.

**Comment by gregorybodnar** [comment] 2019-10-08 19:01
The bot is a bit overzealous here. This needs to get sorted.

**Comment by micahellison** [comment] 2020-11-21 22:31
I tried to reproduce this in Windows (`develop` branch) but ran into a separate bug (#1089) and dropped in a PR for it. With that fix working, I can't reproduce this in Windows. It works fine.

I also can't reproduce this in Ubuntu (w/ WSL, using jrnl 2.5).

Somewhere along the past few releases, this must have been fixed in the resolution to another issue,, so I'm closing this.

**Closed by micahellison** 2020-11-21 22:31 UTC
Labels: :pushpin:, bug
