### ISSUE TITLE
'jrnl -n X' gives 'ValueError: invalid literal for int() with base 10:'

### ISSUE THREAD

**Issue by IosiaLectus** [jrnl-org/jrnl#1317] opened 2021-08-11 20:22 UTC
### Environment
  - `jrnl --diagnostic` output:  
 jrnl: v2.7
Python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
OS: Linux 5.8.0-63-generic
  - Install method:  pipx

### Current Behavior

After an entry,  'jrnl -n 1' returned "ValueError: invalid literal for int() with base 10: '?2004h\x1b[?1049h\x1b[22'". I made another entry after that, and afterwards 'jrnl -n 1' acts as expected, but 'jrnl -n 2', 'jrnl -n 3', etc give the error. The initial entry was written into 'entry.txt' and then entered by 'jrnl < entry.txt'.

### Expected Behavior

I would expect 'jrnl -n #' to return the # most recent entries.

### Repro Steps

Not sure how to reproduce, I can only assume it is due to the particulars of the entry.

**Comment by micahellison** [comment] 2021-08-17 01:59
Hi there, thanks for reporting this. Would you mind opening the journal text file directly with a text editor and copy-pasting the entry that's causing this error? It looks like this might due to something in the way jrnl tries to identify dates in journal entries, but I can't tell without seeing the source data. It would be extra helpful if you're willing to poke at the entry a bit and narrow it down until you can find which characters specifically are causing the error, though I understand that could be a lot of work.

Looking at the quoted part of your error message, it looks like there were control characters in your file, which could be part of the problem. Like maybe these are color codes from text outputted by another program? Either way, it would be nice to be able to reproduce this so we could fix this.

**Comment by micahellison** [comment] 2021-09-06 18:12
Closing this for now. Feel free to comment if you're still running into this.

**Closed as completed by micahellison** 2021-09-06 18:12 UTC
Labels: needs more info
