### ISSUE TITLE
Refactor cli.py

### ISSUE THREAD

**Issue by dbxnr** [jrnl-org/jrnl#817] opened 2020-01-24 04:20 UTC
The argparse code is pretty messy, it predates modern packages such as [Click](https://palletsprojects.com/p/click/).  It's difficult to work with and that makes adding new features unnecessarily difficult.

As a quality of life change, it would be hugely beneficial to refactor the CLI and possibly introduce a package to make it easier to maintain and augment.

Issues #520 #491 #707 #814 #813 #818 are all related.

This wouldn't necessarily break backwards compatibility, however it would be an opportunity to start a discussion about streamlining the CLI (see #814 https://github.com/jrnl-org/jrnl/pull/794#issuecomment-576446133) for future major versions.

**Comment by wren** [comment] 2020-01-25 20:58
Dupe of #707

**Closed by wren** 2020-01-25 20:58 UTC
Labels: duplicate
