### ISSUE TITLE
Does not save jrnl with non-ASCII character 

### ISSUE THREAD

**Issue by atligunn** [jrnl-org/jrnl#811] opened 2020-01-20 13:55 UTC
I noticed that I cant save jrnl with my character set (Icelandic) when using icelandic special characters (ex. þ æ ð ó í). I can write the characters but cant save them. Maybe this issue is with other languages as well? 

Output of some silly jrnl (just for ref)

 
[Compose Entry; press Ctrl+D to finish writing]

Icelandic: Þetta er prufa  
English: This is a test
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==2.0.1', 'console_scripts', 'jrnl')()
  File "/usr/local/lib/python2.7/dist-packages/jrnl/cli.py", line 227, in run
    raw = " ".join(args.text).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

I'm not keen on reading through source code (as of yet, at least) so I can't point out where in the code the fault is or to make a suggestion on the change.

**Comment by wren** [comment] 2020-01-20 20:52
Thank you for the issue report! It looks like you're running jrnl v2+ with Python 2. Can you please update to Python 3, and see if you still experience this issue? Python 3 has better unicode handling that we're relying on since v2.0.

**Comment by yaruson** [comment] 2020-01-24 08:25
I can confirm the bug in Python 2 and that it's working with Python 3 properly.

The only thing is that I had to adjust the path to `python3` interpreter in `~/.local/bin/jrnl`, not sure if that's a proper way of doing this :slightly_smiling_face:

**Comment by wren** [comment] 2020-01-25 21:00
Thank you for verifying that, @yaruson. Closing this as solved in an older version.

**Closed by wren** 2020-01-25 21:00 UTC
Labels: bug

**Comment by friskfrugt** [comment] 2020-02-12 15:38
> I can confirm the bug in Python 2 and that it's working with Python 3 properly.
> 
> The only thing is that I had to adjust the path to `python3` interpreter in `~/.local/bin/jrnl`, not sure if that's a right way of doing this

How do i do that? I have the same issue.

**Comment by wren** [comment] 2020-03-13 04:27
@friskfrugt If you reinstall using Python 3, it should fix your issue.
