### ISSUE TITLE
jrnl returns error with path that has quotes

### ISSUE THREAD

**Issue by Mohsen-Liaghat** [jrnl-org/jrnl#1717] opened 2023-04-02 06:39 UTC
### Diagnostic output

jrnl: v3.3
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
OS: Windows 10

### Current Behavior

jrnl was installed somewhere on the C drive. 
I want to create my journal files on D drive.
now jrnl tries to open a path like this 'C:\\Users\\usename\\"D:'  and the OS return an error

### Expected Behavior

the path of journal files must be same as the user input

### Repro Steps

install  jrnl somewhere on windows.
set the path of journal files on an other drive.

### Debug output

the output is [here](https://drive.google.com/file/d/1qYzrGuGyRSLx_8m3IudL11LWezyu94L_/view?usp=sharing)

**Comment by micahellison** [comment] 2023-04-03 15:43
Hi there @Mohsen-Liaghat, it looks like you may have used quotes when entering the path, which I think is causing the problem. You can fix it by editing the `journal` key in your config file, which you can find by running `jrnl --list`.

I tried to reproduce this issue, and ran into the same problem only when I used quotes. It may seem like a bug, but jrnl is a cross-platform app and quotes are valid characters on non-Windows file systems, which is why it's allowing this to happen.

I'm closing this as a support issue since I don't think there should be any code changes as a result, but please feel free to let us know if the issue persists after you edit the path in your config file.

**Closed as completed** 2023-04-03 15:43 UTC
Labels: support
