### ISSUE TITLE
When adding an entry for today's date, numerous additional entries containing random text are added.

### ISSUE THREAD

**Issue by jwheeler88** [jrnl-org/jrnl#1308] opened 2021-07-22 21:42 UTC
### Environment
  - `jrnl --diagnostic` output: 
jrnl: v2.8.1
Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
OS: Windows 10
- Install method: `pipx`
- Running in: `PowerShell 7.1.3` and `Windows Terminal 1.8.1521.0`
### Current Behavior

When adding an entry for today's date, `jrnl` will add both the entry I typed along with numerous additional entries. The additional entries contains a ton of random text; in my case, it's text from the help docs for `PowerShell` along with a log from `ShareX` which is a screen capture program I have installed.

This occurs whether I omit a date stamp or specify the date explicitly, either with `today` or `now` or some other date format. The issue **only occurs for entries on today** and otherwise works correctly for days in the past or future.

For example, when performing a `jrnl today: testing` I receive the following output:

> [2021-07-22 13:56] ABOUT ALIAS
> ES
> 
> 
> SHORT DESCRIPTION
> 
> Describes how to use alternate names for cmdlets and commands in
> PowerShell.
> 
> 
> LONG DESCRIPTION
> 
> An alias is an alternate name or nickname for a cmdlet or for a command
> element, such as a function, script, file, or executable file. You can use
> the alias instead of the command name in any PowerShell commands.
> 
> To create an alias, use the New-Alias cmdlet. For example, the following
> command creates the "gas" alias for the Get-AuthenticodeSignature cmdlet:
> 
>     New-Alias -Name gas -Value Get-AuthenticodeSignature

Text continues for a while with more help doc information and `ShareX` log information; finishes with:

> 2021-07-22 13:23:33.504 - Hotkey registered: Hotkey: Print Screen, Description: Capture entire screen, Job: PrintScreen
> 2021-07-22 13:23:33.504 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
> 2021-07-22 13:23:33.504 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
> 2021-07-22 13:23:33.504 - Hotkey registered: Hotkey: Ctrl + Shift + Print Screen, Description: Start/Stop screen recording (GIF), Job: ScreenRecorderGIF
> 2021-07-22 13:23:33.506 - HotkeyManager started.
> 2021-07-22 13:23:33.507 - WatchFolderManager started.
> 
> [2021-07-22 13:56] testing

### Expected Behavior

When adding an entry for today's date, `jrnl` should only add the single entry I entered and nothing else.

### Repro Steps

1. Install `jrnl` with `pipx`.
2. Add new entry for today's date, using any of the supported formats to specify the date, including omitting the date stamp altogether. Ex: `jrnl today: test`.
3. The journal *.txt contents for today's date should have the entry added along with additional entries containing random text unrelated to the entry added in step 2.

Debug log for `jrnl today: test`:

> DEBUG    root         Parsed args: Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None, end_date=None, contains=None, strict=False, starred=False, limit=None, excluded=[], edit=False, delete=False, export=False, tags=False, short=False, config_override=[], text=['today:', 'test'])
> DEBUG    root         Reading configuration from file C:\Users\james.wheeler\.config\jrnl\jrnl.yaml
> DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': True, 'highlight': True, 'indent_character': '|', 'journals': {'default': 'C:\\Users\\james.wheeler\\Documents'}, 'linewrap': 79, 'tagsymbols': '@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v2.8.1'}"
> DEBUG    root         Using journal name: default
> DEBUG    root         Write mode: starting
> DEBUG    root         Write mode: cli text detected: ['today:', 'test']
> DEBUG    root         Write mode: appending raw text to journal "default": today: test
> [Entry added to default journal]
> --- Logging error ---
> Traceback (most recent call last):
>   File "c:\users\james.wheeler\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1083, in emit
>     msg = self.format(record)
>   File "c:\users\james.wheeler\appdata\local\programs\python\python39\lib\logging\__init__.py", line 927, in format
>     return fmt.format(record)
>   File "c:\users\james.wheeler\appdata\local\programs\python\python39\lib\logging\__init__.py", line 663, in format
>     record.message = record.getMessage()
>   File "c:\users\james.wheeler\appdata\local\programs\python\python39\lib\logging\__init__.py", line 367, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "c:\users\james.wheeler\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\james.wheeler\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\james.wheeler\.local\bin\jrnl.exe\__main__.py", line 7, in <module>
>     sys.exit(cli())
>   File "c:\users\james.wheeler\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\cli.py", line 35, in cli
>     return run(args)
>   File "c:\users\james.wheeler\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\jrnl.py", line 71, in run
>     write_mode(**kwargs)
>   File "c:\users\james.wheeler\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\jrnl.py", line 151, in write_mode
>     logging.debug("Write mode: completed journal.write()", args.journal_name, raw)
> Message: 'Write mode: completed journal.write()'
> Arguments: ('default', 'today: test')

### Other Information

I have tried reinstalling `jrnl` and restarting my computer but neither resolves the issue.

**Comment by micahellison** [comment] 2021-07-23 03:47
Hi there, thanks for reporting this. I'm not able to reproduce anything quite like this in PowerShell with the Windows Terminal, and I'm wondering if there is something happening that is unique to your PowerShell sessions.

It looks like it is piping text into jrnl, which is something that jrnl can accept, though I don't know why it would be doing that while you are also creating a new entry with command line arguments. I tried but failed to reproduce it by piping into jrnl with command args like so:
```
echo "this will get ignored" | jrnl today: this is the real entry
```
However, without entering anything after `jrnl`, it does create a new entry, which is to be expected:
```
echo "this will be added" | jrnl
```

To start narrowing things down, could you try running your same test in a regular Windows command prompt instead of PowerShell?

**Comment by jwheeler88** [comment] 2021-07-23 17:47
Hi, thanks for the help!

Just tried running the same test in Windows command prompt (separate from Windows Terminal even) and still get the same result.

**Comment by micahellison** [comment] 2021-07-24 17:14
Sorry that didn't work. I'm mystified by this problem.

I'm looking through your initial bug report and I see you're using a directory for your journal -- specifically, your Documents folder. We have some issues with directory-based journals, though they are the opposite of what you're experiencing -- failing to import (#999), rather than importing unexpected data. I also wonder if there is other data in your Documents folder than is being read as journal entries. The entries are stored in this directory structure: `Documents\YYYY\MM\DD.txt`

Could you try using a file-based journal instead (e.g. `Documents\journal.txt`) and let me know if this issue persists?

**Comment by jwheeler88** [comment] 2021-07-27 17:56
Ahh, I wasn't aware I was working out of a directory-based journal; I had assumed when I gave it the path to the directory that it would then create a journal file and work out of that. But it makes more sense that a user would like to configure the name of the journal as well.

After working from a `Documents\journal.txt` it works correctly now. I also noticed that I was never prompted for encryption before like I just was when working with a file.

Thank you for the help!

**Comment by micahellison** [comment] 2021-07-31 18:26
Glad to help! Thanks for reporting back. I'm going to close this since the directory journal bug is documented elsewhere and we can't figure out how to repro the strange PowerShell help issue, but if ever anyone does figure it out, feel free to chime in.

**Closed as completed by micahellison** 2021-07-31 18:26 UTC
Labels: windows, support
