### ISSUE TITLE
[Question] Using external editor and timestamp at once?

### ISSUE THREAD

**Issue by brunoduran** [jrnl-org/jrnl#513] opened 2017-12-04 13:17 UTC
I have some lengthy notes to add. I would want to  use the external editor. Adding a timestamp is easy:
```
jrnl yesterday: Header. Body.
```
and opening the external editor too:
```
jrnl
```

Now I could do it in two steps:

```
jrnl yesterday: Header.
jrnl --edit # and search for the entry
```

But it is not practical. Is it possible to do it in one step? 

Thanks,
Bruno

**Comment by maebert** [comment] 2017-12-05 23:26
Not currently, but I'll think about how to best add this!

**Comment by eshanmind** [comment] 2018-03-01 22:39
Since the timestamp is also included in every entry at the top, we could set it up so that whenever you save an entry with an editor, it parses the beginning for a date.

**Comment by stephanmax** [comment] 2018-05-12 18:10
I am using jrnl quite heavily these days to get Facebook activity over into my journal. Would you mind me taking a shot at this, @maebert?

**Comment by curioussavage** [comment] 2018-11-14 21:55
@stephanmax did you work on it at all? I'm tempted to just hack it into the `run` function since I really want this

**Comment by wren** [comment] 2019-07-16 04:09
@curioussavage @stephanmax Hi, new maintainer here. I like this idea, and am open to a PR for it. Please just run the high level idea for your proposal through here so we can minimize the back and forth when it comes time to code.

Mainly, I would like to know what this would actually look like in one step. 

Thanks!

**Comment by alichtman** [comment] 2019-11-16 14:08
Duplicate of #383.

**Closed** 2019-11-18 15:51 UTC
Labels: :star:, enhancement
