### ISSUE TITLE
Arguments with single dash don't work

### ISSUE THREAD

**Issue by lamyergeier** [jrnl-org/jrnl#1252] opened 2021-05-31 02:48 UTC
### Environment
  - `jrnl --diagnostic` output:  

``` 
$ jrnl --diagnostic
jrnl: v2.8.1
Python: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
OS: Linux 5.4.0-73-generic
```

  - Install method:  pipx and brew (tried both methods)

### Current Behavior

Any argument beginning with single dash is not working:

```bash
$ jrnl -to today
Traceback (most recent call last):
  File "/home/nikhil/.local/bin/jrnl", line 8, in <module>
    sys.exit(cli())
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 35, in cli
    return run(args)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 73, in run
    search_mode(**kwargs)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 179, in search_mode
    _display_search_results(**kwargs)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 340, in _display_search_results
    print(exporter.export(journal, args.filename))
AttributeError: 'NoneType' object has no attribute 'export'
```
### Expected Behavior

Filter is not working.

### Repro Steps

```
$ jrnl -to today --debug
DEBUG    root         Parsed args: Namespace(config_override=[], contains=None, day=None, debug=True, delete=False, edit=False, end_date='today', excluded=[], export=False, filename=None, limit=None, month=None, on_date=None, postconfig_cmd=None, preconfig_cmd=None, short=False, starred=False, start_date=None, strict=False, tags=False, text=[], today_in_history=False, year=None)
DEBUG    root         Reading configuration from file /home/nikhil/.config/jrnl/jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'indent_character': '|', 'linewrap': 79, 'timeformat': '%Y-%m-%d %H:%M', 'default_hour': 9, 'default_minute': 0, 'display_format': 'short', 'editor': 'codium --wait', 'encrypt': False, 'highlight': True, 'journals': {'default': '~/Documents/Mobile/Documents/PortableNotes/PortableNotesSrc/Journal/Journal.txt', 'time': '~/Documents/Mobile/Documents/PortableNotes/PortableNotesSrc/Journal/Time.txt'}, 'tagsymbols': '@', 'template': False, 'version': 'v2.4.5'}"
DEBUG    root         Using journal name: default
DEBUG    root         opened PlainJournal with 4 entries
Traceback (most recent call last):
  File "/home/nikhil/.local/bin/jrnl", line 8, in <module>
    sys.exit(cli())
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 35, in cli
    return run(args)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 73, in run
    search_mode(**kwargs)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 179, in search_mode
    _display_search_results(**kwargs)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 340, in _display_search_results
    print(exporter.export(journal, args.filename))
AttributeError: 'NoneType' object has no attribute 'export'
```

Also when composing if the title begins with `@`, then I get the same error

```bash
$ jrnl time '@Breakfast' --debug
DEBUG    root         Parsed args: Namespace(config_override=[], contains=None, day=None, debug=True, delete=False, edit=False, end_date=None, excluded=[], export=False, filename=None, limit=None, month=None, on_date=None, postconfig_cmd=None, preconfig_cmd=None, short=False, starred=False, start_date=None, strict=False, tags=False, text=['time', '@Breakfast'], today_in_history=False, year=None)
DEBUG    root         Reading configuration from file /home/nikhil/.config/jrnl/jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'indent_character': '|', 'linewrap': 79, 'timeformat': '%Y-%m-%d %H:%M', 'default_hour': 9, 'default_minute': 0, 'display_format': 'short', 'editor': 'codium --wait', 'encrypt': False, 'highlight': True, 'journals': {'default': '~/Documents/Mobile/Documents/PortableNotes/PortableNotesSrc/Journal/Journal.txt', 'time': '~/Documents/Mobile/Documents/PortableNotes/PortableNotesSrc/Journal/Time.txt'}, 'tagsymbols': '@', 'template': False, 'version': 'v2.4.5'}"
DEBUG    root         Using journal name: time
DEBUG    root         opened PlainJournal with 17 entries
Traceback (most recent call last):
  File "/home/nikhil/.local/bin/jrnl", line 8, in <module>
    sys.exit(cli())
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 35, in cli
    return run(args)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 73, in run
    search_mode(**kwargs)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 179, in search_mode
    _display_search_results(**kwargs)
  File "/home/nikhil/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/jrnl.py", line 340, in _display_search_results
    print(exporter.export(journal, args.filename))
AttributeError: 'NoneType' object has no attribute 'export'
```

**Comment by wren** [comment] 2021-05-31 05:35
Hi, and thanks for reporting this bug! It looks like `display_format: short` is what's causing this problem for you. If you take that out of your config, then you should stop seeing this error. We still need to fix this, but in the meantime, a workaround if you still want to use the "short" format would be to add `--short` when you want to see that format.

**Comment by wren** [comment] 2021-05-31 05:41
Oh, to clarify, the part about starting entries with `@`. If you enter only tags to jrnl (and no other content), it then assumes you are attempting to search your entries for those tags. That's why you're also seeing that error there. From my quick research, I expect this error would happen with the short format on any attempt to search in jrnl. Sorry about that!

**Comment by lamyergeier** [comment] 2021-05-31 08:38
I have an idea to solve this issue, we can have an argument `-c`, which explicitly tells the software  to compose along with the default mode without any arguments.

**Comment by wren** [comment] 2021-06-05 02:48
I'm fairly certain that the problem above was caused by `format: short` in your config. Did removing fix your problem?

As for the compose suggestion, can you please elaborate a bit on your use case? Do you regularly write entries composed entirely of tags?

**Comment by lamyergeier** [comment] 2021-06-05 09:51
> Did removing fix your problem?

Yes

# Use Case

- The main barrier to journaling is that it is overwhelming to new people. So, if what we need to journal, can be recorded in least possible number of words the better it is. In some cases, tags provide enough information that  we need.
- For example:
  - I have a separate journal which I use to record my routine.
  - I want to keep at least 6 hrs of gap between lunch and dinner and I want to do daily fasting for 12 hours. So, for this purpose I want to know when I had food, and when I went to bed and got up.
  - With @Breakfast tag: I want to know if I am consistently having breakfast at the same time or how much is it deviating.

---

You can see that in these cases where there is no additional sentence for an entry and the title is just a tag, `--format --short` makes much sense here!

```bash
2021-05-31 12:09 @Breakfast
2021-05-31 17:57 @Dinner
2021-06-01 06:18 @Breakfast
2021-06-02 03:24 @Snacks
2021-06-02 13:07 @Lunch
2021-06-03 10:29 @Breakfast
```

**Comment by micahellison** [comment] 2021-06-19 18:46
I'm spinning off the `display_format: short` issue into its own bug for easy tracking: #1263

**Comment by wren** [comment] 2021-06-19 18:49
Ok, I think all issues mentioned here are either resolved or have a new issue made for them, so I'm closing this. Please speak up if there's anything else. Thank you!

**Closed as completed by wren** 2021-06-19 18:49 UTC
Labels: support
