### ISSUE TITLE
Confusing error message when user does not have a keyring backend installed

### ISSUE THREAD

**Issue by jonaths** [jrnl-org/jrnl#851] opened 2020-02-15 23:29 UTC
## Bug report

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`) 2.2
  - How you installed Jrnl pip3 install jrnl
  - Operating system [MacOS, Linux, Windows?] Ubuntu 18.04

* **What is the current behavior?**
An error is shown. Here is the trace. 

```
-> jrnl
[Compose Entry; press Ctrl+D to finish writing]

holaEnter password for new journal: 
Enter password again: 
Passwords did not match, please try again
Enter password for new journal: 
Enter password again: 
Do you want to store the password in your keychain? [Y/n] n
Traceback (most recent call last):
  File "/home/jonathan/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/jonathan/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 94, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonathan/.local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/home/jonathan/.local/lib/python3.6/site-packages/jrnl/cli.py", line 362, in run
    journal = open_journal(journal_name, config)
  File "/home/jonathan/.local/lib/python3.6/site-packages/jrnl/Journal.py", line 397, in open_journal
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "/home/jonathan/.local/lib/python3.6/site-packages/jrnl/EncryptedJournal.py", line 46, in open
    self.password = util.create_password(self.name)
  File "/home/jonathan/.local/lib/python3.6/site-packages/jrnl/util.py", line 62, in create_password
    set_keychain(journal_name, None)
  File "/home/jonathan/.local/lib/python3.6/site-packages/jrnl/util.py", line 101, in set_keychain
    import keyring
  File "/home/jonathan/.local/lib/python3.6/site-packages/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/home/jonathan/.local/lib/python3.6/site-packages/keyring/core.py", line 192, in <module>
    init_backend()
  File "/home/jonathan/.local/lib/python3.6/site-packages/keyring/core.py", line 96, in init_backend
    filter(limit, backend.get_all_keyring()),
  File "/home/jonathan/.local/lib/python3.6/site-packages/keyring/util/__init__.py", line 22, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/jonathan/.local/lib/python3.6/site-packages/keyring/backend.py", line 216, in get_all_keyring
    _load_plugins()
  File "/home/jonathan/.local/lib/python3.6/site-packages/keyring/backend.py", line 207, in _load_plugins
    log.exception("Error initializing plugin %s." % ep)
TypeError: not all arguments converted during string formatting
```

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
- pip3 install jrnl
- Edit config file and set a new jrnl file location and set encryption to true. 
- Typed jrnl and was asked for entry and new password. 
- Asked to store in keychain: if yes or no still the same error appears. 

* **What is the expected behavior?**
I wouold expect to store my entry. If encryption is set to false it works. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by wren** [comment] 2020-03-07 19:25
Hi, sorry for the slow reponse on this. We're looking into it. 

The stack trace looks like you're running on Windows? Is that correct?

**Comment by micahellison** [comment] 2020-03-07 19:45
I was able to repro this on the WSL w/ Ubuntu 18.04.2 LTS. It looks like there's no keyring backend in WSL.

**Comment by wren** [comment] 2020-03-07 20:49
It looks like installing a keyring backend solves this problem. I don't think we should pick one for people, but we can output a nicer message with a link to the docs on how to deal with this problem. 

So, this fix needs:
- Catch keyring exception(s)
- Update documentation about how to install a keyring backend (with link to https://pypi.org/project/keyring/#third-party-backends)
- Output a message to user instead of the stack trace

**Comment by wren** [comment] 2020-03-13 03:39
Dupe of #788?

**Comment by micahellison** [comment] 2020-04-04 19:52
An update on this - using Ubuntu on WSL, I can reproduce the issue if I install jrnl with pip, but not with pipx, where it works fine.

I'd still like a better solution than dumping a stacktrace to the user, but I thought this workaround might help others with this problem in the meantime.

**Comment by eshrh** [comment] 2020-05-26 13:09
This also happens in a poetry shell. Interestingly, it even happens if the user chooses "no" when asked if they want to store their password in the keyring. I'll try to look into why this happens.

**Comment by eshrh** [comment] 2020-05-26 13:22
The current code looks like this:
```
if yesno("Do you want to store the password in your keychain?", default=True):
        set_keychain(journal_name, pw)
    else:
        set_keychain(journal_name, None)
```

set_keychain when password is None does the following:
```
try:
            keyring.delete_password("jrnl", journal_name)
except keyring.errors.PasswordDeleteError:
            pass
```
This is a little bit confusing. There's obviously no need to delete the password when we haven't even added it yet!

**Closed** 2020-05-30 19:43 UTC
Labels: :pushpin:, bug
