### ISSUE TITLE
unable to create first jrnl after setup

### ISSUE THREAD

**Issue by jrmoreau** [jrnl-org/jrnl#810] opened 2020-01-19 04:43 UTC
```
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 227, in run
    journal.write()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 181, in write
    journal = self._encrypt(journal)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 76, in _encrypt
    iv = Random.new().read(AES.block_size)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```
* **Please tell us about your environment:**

jrnl version 1.9.8
installed with home-brew

macOS Catalina 10.15.2

Just tried to set it up and make my first entry via Quickstart guide. After setting my encryption password and trying to do my first entry I get the error above.

**Comment by wren** [comment] 2020-01-20 21:09
Closing as dupe of #781 

The short version is that `brew install` is currently broken. Please use `pip install` for now.

**Closed by wren** 2020-01-20 21:09 UTC
Labels: duplicate, support
