### ISSUE TITLE
Ability to specify different editors on the command line.

### ISSUE THREAD

**Issue by jayrod** [jrnl-org/jrnl#873] opened 2020-03-11 15:11 UTC
## Feature Request

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **What is the motivation / use case for changing the behavior?**

I love to wrap jrnl commands that go along with things I want to document in my process. I therefore have a bash script for starting a journal like this.

```
function jj {
    echo 'Some template'
    read
    jrnl @$MACHINE $REPLY

}
```

This works farily well but I would also like to possibly add an --edit flag after this and have whatever is in the editor also be tagged. So perhaps this just means opening said editor with the tag string at the beginning of it. 

* **Please provide examples of the usage**
jrnl @$MACHINE $REPLY --edit

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by wren** [comment] 2020-03-13 03:25
This seems like maybe a dupe of #874.

Can you clarify a bit what you're looking to accomplish? Would using the script above followed by `jrnl -1 --edit` work for what you're intending?

**Comment by jayrod** [comment] 2020-03-13 11:56
Yes.. I believe they are duplicate. Not sure why I did that, I feel like in my head they were different.

**Comment by jayrod** [comment] 2020-03-13 12:02
crap.. they are different.. So... I was not clear. But even if you just add an --edit flag it does NOT NOT prepend the @MACHINE tag in the opened editor.

**Comment by wren** [comment] 2020-05-16 17:40
If I understand this correctly, then this is a dupe of 906. Keeping 906 because it states the problem more clearly. 

Please let us know if this is actually a different issue!

**Closed by wren** 2020-05-16 17:40 UTC
Labels: duplicate, enhancement
