### ISSUE TITLE
Misaligned settings if --encrypt aborted after password set.

### ISSUE THREAD

**Issue by MarkHedleyJones** [jrnl-org/jrnl#436] opened 2016-08-20 21:45 UTC
Hi there,
Jrnl is a great program. I've only recently found it, but am loving its ability to manage a journal store so far.
I have started an integration plug-in for dmenu-extended for jrnl and one minor thing I've found is the following:

```
jrnl default --encrypt
```

Set a password, but when asked if you want to store the password in the keychain - hit Ctrl+c (abort).
Now the journal is encrypted, but the configuration setting in `~/.jrn_config` is set as

```
"encrypt": false
```

This renders jrnl unable to open the default journal as it doesn't know to decrypt it first.
It's fixed if you go and manually change the setting yourself, but somebody could run into trouble if they didn't figure to do this and they lost power at that critical moment.

Cheers,

Mark

**Comment by wren** [comment] 2019-07-21 05:22
Does this still happen with v2.0?

**Comment by gregorybodnar** [comment] 2019-09-28 18:30
It's there a way to trigger exceptions with behave? I don't know enough about it to say either way, but it might be a good thing to test for if we can.

**Comment by wren** [comment] 2019-09-30 16:05
I'm not sure about exceptions, but I agree that we should look into it.

I know we can tell behave to press certain keys at prompts, so maybe a `ctrl` + `c` would work for this issue? Although I'm not sure how modifier keys work in behave.

**Comment by pspeter** [comment] 2019-11-23 09:26
Behave let's you create arbitrary steps. Just create a new step definition that raises an Exception and you can use that. No need to simulate keys.

```python
@When("the user presses ctrl-c")
def keyboard_interrupt():
	raise KeyboardInterrupt
```

**Comment by wren** [comment] 2020-01-25 20:50
Has anyone confirmed if this still happens on current version?

**Comment by jon-mqn** [comment] 2020-05-27 15:05
Couldn't replicate this issue with the following installation:

-  jrnl v2.4.2
- Python 3.8.2
- Ubuntu 20.04 LTS on Windows 10 x86_64

Ctrl+c at the yes/no prompt just stops the program without encrypting the journal:

```
Enter password for new journal:
Enter password again:
Do you want to store the password in your keychain? [Y/n] Traceback (most recent call last):
  File "/home/helena/.local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 430, in run
    encrypt(journal, filename=args.encrypt)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 247, in encrypt
    new_journal = EncryptedJournal.from_journal(journal)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/EncryptedJournal.py", line 93, in from_journal
    else util.create_password(other.name)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/util.py", line 60, in create_password
    if yesno("Do you want to store the password in your keychain?", default=True):
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/util.py", line 115, in yesno
    response = input(prompt)
KeyboardInterrupt
```

I do run into something else that might require a new issue:

I am trying to encrypt a journal without having the password stored in a keyring (getting the backend setup on WSL is overkill for what I want). When enter "no" at the yes/no prompt, I get keyrring errors and the journal never gets encrypted. Is this intentional?

Example:

After setting up a journal named "private" in ~/.config/jrnl/jrnl.yaml I quickly add two entries.

```
> jrnl private -n 2
2020-05-27 09:00 here is a test of the private

2020-05-27 15:55 This is another test

> jrnl private --encrypt
Enter password for new journal:
Enter password again:
Do you want to store the password in your keychain? [Y/n] n
Traceback (most recent call last):
  File "/home/helena/.local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 430, in run
    encrypt(journal, filename=args.encrypt)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/cli.py", line 247, in encrypt
    new_journal = EncryptedJournal.from_journal(journal)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/EncryptedJournal.py", line 93, in from_journal
    else util.create_password(other.name)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/util.py", line 63, in create_password
    set_keychain(journal_name, None)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/jrnl/util.py", line 106, in set_keychain
    keyring.delete_password("jrnl", journal_name)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/keyring/core.py", line 68, in delete_password
    _keyring_backend.delete_password(service_name, username)
  File "/home/helena/.local/pipx/venvs/jrnl/lib/python3.8/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

Looking at the entries again, I see that they are still in plain text:

```
> jrnl private -n 2
2020-05-27 09:00 here is a test of the private

2020-05-27 15:55 This is another test
```

**Comment by eshrh** [comment] 2020-05-28 02:49
I believe I know why this is happens. 
`journal.config["encrypt"] = True`
Is set before the encryption actually happens. I'll be submitting a PR for this shortly.

@jon-mqn 
I ran into this same problem a few days ago while working on this. It probably not intentional. I clearly said I don't want to keychain my password, why is it still trying to? 
This problem will be resolved by PR #964 if it is merged. 

The reason this happens is that the `set_keychain` function is overloaded. It is meant to set and remove keychain items. However, it is for some reason also used to set a password as None in the keychain.

**Comment by jon-mqn** [comment] 2020-05-28 07:33
@eshrh Ah I should have seen that this issue was #851. Well that's great, I look forward to the PR being merged. Thanks for your work on this!

**Comment by eshrh** [comment] 2020-05-29 16:03
I also cannot reproduce this problem on 2.4.2 on arch. Looks like this is close-able then?

**Comment by wren** [comment] 2020-07-07 07:12
Yup, closeable.

Sorry for the slow reply on this. The lockbot drowned most of my notifications.

**Closed by wren** 2020-07-07 07:12 UTC
Labels: :pushpin:, bug
