### ISSUE TITLE
Encryption Python AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by gwpantazes** [jrnl-org/jrnl#800] opened 2020-01-15 00:04 UTC
## Bug report

* **Please tell us about your environment:**
  - Jrnl version: 1.9.8
  - How you installed Jrnl: via Homebrew
  - Operating system: MacOS

* **What is the current behavior?**

Anything that uses encryption fails, such as actions like `jrnl --encrypt` on an unencrypted journal, or `jrnl --edit` for an encrypted journal file. Consequently, changes made during `--edit` are lost, because the encryption / file-writing fails.

In each of the different reproducing actions, the same error causes the failure: `AttributeError: module 'time' has no attribute 'clock'`.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**

0. The journal file doesn't have to exist yet to run the following steps, so it might be easiest to specify some brand new file location in `~/.jrnl_config`.
1. Make sure the "default" journal is set to `"encrypt": false` in `~/.jrnl_config`. 
2. Run `jrnl --encrypt`.
3. Enter a password at the "Enter new password:" prompt.
3. Observe an error/traceback due to `AttributeError: module 'time' has no attribute 'clock'`  

* **What is the expected behavior?**
There would be no error. Encryption would work as it does normally.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

*Encrypting a new journal*
```
➜  ~ jrnl test --encrypt
Enter new password:
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 257, in run
    encrypt(journal, filename=args.encrypt)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 79, in encrypt
    journal.write(filename)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 181, in write
    journal = self._encrypt(journal)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 76, in _encrypt
    iv = Random.new().read(AES.block_size)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

*Editing an encrypted Journal*
```
➜  ~ jrnl --edit
[1 entry modified]
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 290, in run
    journal.write()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 181, in write
    journal = self._encrypt(journal)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 76, in _encrypt
    iv = Random.new().read(AES.block_size)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/usr/local/Cellar/jrnl/1.9.8_2/libexec/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by dbxnr** [comment] 2020-01-15 02:06
```time.clock``` has been removed from Python 3.8 which is the immediate cause of this error

Can you post the output of ```python -m pycrypto```?

**Comment by gwpantazes** [comment] 2020-01-15 19:41
Sorry if I'm doing this incorrectly, I'm inexperienced when it comes to Python.

Here is the output for the python installation that is actually being used by the homebrew jrnl installation:
```
➜ /usr/local/Cellar/jrnl/1.9.8_2/libexec/bin/python3 -m pycrypto
/usr/local/Cellar/jrnl/1.9.8_2/libexec/bin/python3: No module named pycrypto
```

And here is the output for my "main" python installation on the machine:
```
➜ python3 -m pycrypto
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: No module named pycrypto
```

And here is the output for some other random python installation on my machine, for comparison:
```
➜ /usr/local/opt/python/bin/python3.7 -m pycrypto
/usr/local/opt/python/bin/python3.7: No module named pycrypto
```

Is `pycrypto` something that doesn't come with core python / needs to be installed via `pip`?

Based on your question, I feel like I might be doing something wrong / it's a bit weird that none of the installations have it. 

Should I step back through jrnl versions to check for `pycrypto` until I find one that shows up? Since it seems like the issue is with whatever python is getting paired, and potentially whether pycrypto is being properly installed on installation of `jrnl`?

**Comment by dbxnr** [comment] 2020-01-16 00:58
```pycrypto``` is the library which is calling ```time.clock```, upgrading it might solve the problem however I'm not familiar with how brew manages its python libraries.

The version of jrnl which brew installs is very outdated (hence the error), pip is the recommended way to get jrnl.

You could try uninstalling jrnl from brew, then running ```python3 pip install jrnl```.  If that doesn't work, follow [the instructions](https://pip.pypa.io/en/stable/installing/) to install pip and try running the command again.

**Comment by augustgerro** [comment] 2020-01-20 18:12
Its broken brew dependencies. Brew manifest wants last python version

**Comment by wren** [comment] 2020-01-20 21:12
Closing as dupe of #781 

The short version is that `brew install` is currently broken. Please use `pip install` for now. Sorry!

**Closed** 2020-01-20 21:14 UTC
Labels: bug, duplicate
