### ISSUE TITLE
Application failing to start in MacOS after installing 4.1 in HomeBrew

### ISSUE THREAD

**Issue by ercpereda** [jrnl-org/jrnl#1827] opened 2023-11-07 04:11 UTC
### Diagnostic output

```bash
$ jrnl --diagnostic
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 5, in <module>
    from jrnl.main import run
  File "/usr/local/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/jrnl/main.py", line 8, in <module>
    from rich.logging import RichHandler
  File "/usr/local/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/rich/logging.py", line 15, in <module>
    from .traceback import Traceback
  File "/usr/local/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/rich/traceback.py", line 23, in <module>
    from pygments.lexers import guess_lexer_for_filename
ModuleNotFoundError: No module named 'pygments'
```

### Current Behavior

The command `jrnl` fails to resolve some dependencies and doesn't start.

### Expected Behavior

It should install all the dependencies

### Repro Steps

```bash
$ brew update && brew install jrnl
```

```bash
$ jrnl
```

### Debug output

```bash
$ jrnl --debug lorem ipsum
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 5, in <module>
    from jrnl.main import run
  File "/usr/local/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/jrnl/main.py", line 8, in <module>
    from rich.logging import RichHandler
  File "/usr/local/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/rich/logging.py", line 15, in <module>
    from .traceback import Traceback
  File "/usr/local/Cellar/jrnl/4.1/libexec/lib/python3.12/site-packages/rich/traceback.py", line 23, in <module>
    from pygments.lexers import guess_lexer_for_filename
ModuleNotFoundError: No module named 'pygments'
```

**Comment by micahellison** [comment] 2023-11-07 15:22
Hi @ercpereda, thanks for filing this.

Unfortunately I don't have a Mac and can't reproduce this with brew on WSL/Ubuntu (jrnl v4.1 installs and runs just fine). However, this is the same error reported in #1823 in the previous Homebrew release so it's clearly a pattern for at least some Mac users.

If anyone else on a Mac can or can't reproduce this, please let us know, along with any relevant information (OS version, etc.).

As far as a resolution goes, you will probably have better luck with the [Homebrew community](https://github.com/Homebrew/homebrew-core/issues/new/choose), since this seems to be an issue with how they're packaging jrnl. They have a lot of additional troubleshooting prompts that might help narrow down the issue. If you do that, feel free to link back to this issue so others can find it.

And lastly, as a workaround, using pipx to install jrnl should work just fine (though if that doesn't work, please let me know here also):
```
brew uninstall jrnl
brew install pipx
pipx install jrnl
```

**Comment by ercpereda** [comment] 2023-11-07 18:31
Hi @micahellison 
Thank you for your answer.
I tried the **pipx** route and got a different issue.
After searching around looks like is a problem with python 3.12

```
$ pipx install jrnl
Fatal error from pip prevented installation. Full pip output in file:
    /Users/<myuser>/.local/pipx/logs/cmd_2023-11-07_13.29.25_pip_errors.log

Some possibly relevant errors from pip install:
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Error installing jrnl.
```

**Comment by micahellison** [comment] 2023-11-07 18:53
Sorry that workaround has its own issues. I know that it's not just a problem with Python 3.12 because I've tried both approaches on Ubuntu with Python 3.12 without issues, but I'm not sure what makes things different on the Mac (or perhaps your Mac environment in particular).

If you'd like to share that pip output log file mentioned in your message (`cmd_2023-11-07_13.29.25_pip_errors.log`), that might help me narrow it down.

**Comment by ercpereda** [comment] 2023-11-07 19:08
Yes, looks like the issue is with my setup in this case. My pipx is using python 3.10

```
Traceback (most recent call last):
  File "/Users/<user>/.local/pipx/shared/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
```
Thank you

**Comment by micahellison** [comment] 2023-11-07 21:15
Thanks for reporting back! I think (and hope) the brew issue is similar too -- a consequence of running an unisolated environment that has still has remnants of older configurations.

Though if anyone can help narrow this down, I'm sure it'd be much appreciated by others that run into it.

**Comment by ercpereda** [comment] 2023-11-08 00:40
I did some cleanup and made it work with **pipx**. 
Homebrew is still failing, so I'll keep the issue open.
Thank you for the assistance @micahellison 
```
$ brew uninstall pipx
$ rm -rf /Users/<myuser>/.local/pipx
$ brew install pipx
$ pipx install jrnl
```

**Comment by utopiatopia** [comment] 2023-11-16 18:21
I'm unable to replicate this issue on MacOS 14.2b3. What version of MacOS are you running? I've had issues with other formulas (specifically rust) being unable to install on older versions (MacOS 10.13). Also, can you confirm that pycparser is installed via Homebrew?

**Comment by ercpereda** [comment] 2023-11-17 01:57
I'm using MacOS 13.4, I'll try to update soon and see if that was the issue.
Thank you

**Comment by micahellison** [comment] 2024-02-02 02:35
I'm closing this since I don't think there's any action for us to take, but feel free to comment on this issue if you have more information on the problem.

**Closed as completed by micahellison** 2024-02-02 02:35 UTC
Labels: needs more info, support
