### ISSUE TITLE
jrnl shows wrong weekday

### ISSUE THREAD

**Issue by jao2022** [jrnl-org/jrnl#1597] opened 2022-09-15 13:14 UTC
### Diagnostic output

jrnl: v3.2
Python: 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)]
OS: Darwin 21.6.0

### Current Behavior

jrnl displays the wrong weekday when "%A, %B %d %H:%M" is set for the timeformat. Today is September 15th, so journal entries from today should say "Thurday, September 15 09:00" However, jrnl is reporting "Saturday, September 15th 09:00". When I open 'jrnl --edit' my weekdays have changed to be two days ahead.

### Expected Behavior

jrnl should display appropriate day of the week corresponding ot the date of the journal entry

### Repro Steps

1. set your timeformat to "%A, %B %d %H:%M" 
2. Create a new encrypted journal
3. Make a jrnl entry
4. enter 'jrnl -to today' on cmd prompt to see jrnl entries
5. notice that jrnl is reporting the wrong day

### Debug output

jrnl -to today --debug
DEBUG    root         Parsed args: Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None, end_date='today', contains=None, strict=False, starred=False, limit=None, excluded=[], edit=False, delete=False, change_time=None, export=False, tags=False, short=False, config_override=[], config_file_path='', text=[])
DEBUG    root         Reading configuration from file /Users/jaopenshaw/.config/jrnl/jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '/usr/bin/vim', 'encrypt': True, 'highlight': True, 'indent_character': '|', 'journals': {'default': '/Users/jaopenshaw/Documents/journal.txt'}, 'linewrap': 79, 'tagsymbols': '#@', 'template': False, 'timeformat': '%A, %B %d %H:%M', 'version': 'v3.2'}"
DEBUG    root         Using journal name: default

**Comment by micahellison** [comment] 2022-09-17 18:54
Thanks for reporting this, @jao2022. I reproduced the issue on my Windows 10 machine also. Today's date (a Saturday) is saved as a Monday, though the rest of the date string is correct. It is a problem with how jrnl stores the date, rather than how it displays it.

Looks like the journal doesn't need to be encrypted for this to happen. Here are some simpler steps to repro:
* Define a new journal in your config with `timeformat: '%A, %B %d %H:%M'`
* Write an entry without specifying the date
* Look at the contents of the journal

The weekday seems to be consistently 2 days late. The abbreviated weekday (`%a` for "Mon" instead of `%A` for "Monday") is also showing the same symptom.

The best (albeit incomplete) workaround I can think of right now is to use `timeformat: '%c'`, which is showing the correct day of the week, though it is still a shorter and more abbreviated than the format above.

**Comment by micahellison** [comment] 2022-09-24 18:39
Update: I was just talking about this with @wren, who pointed out that the year was gone from this timestamp, which explains why it's been so erratic.

The date picker must be choosing some arbitrary year for figuring out the weekday. If you change your format to this, it will work fine:
```
timeformat: '%A, %B %d %Y %H:%M'
```

I'm remove the "bug" label from this issue and closing it, since it's not realistic to support jrnl without years. Still, feel free to respond to this thread with any questions.

**Closed as completed by micahellison** 2022-09-24 18:39 UTC
Labels: support, :pushpin:
