### ISSUE TITLE
Errors installing 2.0.0rc2

### ISSUE THREAD

**Issue by emceeaich** [jrnl-org/jrnl#622] opened 2019-07-16 05:46 UTC
I'm trying to install 2.0.0rc2 via pip3 on Ubuntu 19.04

```
sudo -H pip3 install jrnl==2.0.0rc2
```
I'm getting an error while trying to install `cryptography`

```
 x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c build/temp.linux-x86_64-3.7/_openssl.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_openssl.o
  build/temp.linux-x86_64-3.7/_openssl.c:493:10: fatal error: openssl/opensslv.h: No such file or directory
   #include <openssl/opensslv.h>
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
When I check my openssl library, apt-get reports that I have the most current version.

**Comment by emceeaich** [comment] 2019-07-16 06:22
I got past that error by installing the headers files with:

```
sudo apt-get install libssl-dev
```

But compilation is still failing with errors.

**Comment by gregorybodnar** [comment] 2019-07-16 06:27
Duplicate of #610 
The SSL headers conflict with the definitions in crypto 1.4. My openssl version was 1.1.1.

**Comment by wren** [comment] 2019-07-20 17:26
Yup, this is a dupe of #610. The fix is already committed and will be in rc3.

**Closed by wren** 2019-07-20 17:26 UTC
Labels: duplicate
