### ISSUE TITLE
Can't pass command line arguments with spaces to editor

### ISSUE THREAD

**Issue by tleish** [jrnl-org/jrnl#491] opened 2017-07-25 20:07 UTC
The following command starts macvim, opens the journal file with a pre-vimrc that sets the syntax to Markdown

```
$ macvim -f -c 'setf markdown' ~/Dropbox/Journal/2017.md'
```

However, when I used this same command in the .jrnl_config I get an error:

#### .jrnl_config
```javascript
{
  "editor": "macvim -f -c 'setf markdown'",
}
```

#### Error
```
$ jrnl -1 --edit
Error detected while processing pre-vimrc command line:
E20: Mark not set
Press ENTER or type command to continue
```

Any suggestions on how to fix this?

**Comment by wadegbow** [comment] 2017-11-06 18:05
Pretty sure it's happening because the command just get's split by any whitespace, including the stuff in single quotes. 

https://github.com/maebert/jrnl/blob/master/jrnl/util.py#L133

Not sure of an elegant way to fix this by changing your editor value. Might try making a branch using shlex split, because it keeps the stuff in single quotes intact. 

For anyone wondering, the reason this would be cool is so that you can journal with vim and have vim-pencil and goyo start automatically.

**Comment by cecep2** [comment] 2017-11-27 23:18
I solved this by adding a simple function to my `.vimrc` which sets the desired defaults for the jrnl app:

```
function! JrnlSettings()
    set ft=pandoc
    Goyo
endfunction
command! JrnlSettings call JrnlSettings()
```

In my case it turns on [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) for Markdown editing and [Goyo](https://github.com/junegunn/goyo.vim) for distraction-free writing. Then in your `.jrnl_config` you use this:

```
{
  "editor": "macvim -f -c JrnlSettings",
}
```

**Comment by dankozlowski** [comment] 2018-06-28 17:21
@cecep2 We should totally get this in to the docs!

**Comment by BenKettlewell** [comment] 2019-07-17 02:00
I'm trying to solve a similar issue. I renamed the journals from .txt to .md and updated the .jrnl_config to point to the new path. I can edit them directly with `vim /path/to/journal.md` and my [vim highlighting](https://github.com/plasticboy/vim-markdown) plugin works fine. The problem is if I use `jrnl @tag --edit` it still assumes it's text.
A temporary workaround is to set the file type manually in vim with `:set ft=markdown` but having to do this every time I open it is a drag.

**Comment by gregorybodnar** [comment] 2019-07-17 02:48
I think the problem that the OP was seeing is vim interpreting the single quote as a jump-to-mark. The error is correctly indicating that there is no mark for _s_. But I'm baffled as to why it would happen when called from jrnl but not when called on the command line.

@BenKettlewell You should be able to automatically call `:set ft=markdown` on a matched path. Check the file pattern that is used when jrnl creates the temp file. I'm getting something like `/tmp/jrnlXXXXXXXX.txt`. So you might get by with `autocmd BufRead /tmp/jrnl*.txt set ft=markdown` in your `.vimrc`.

**Comment by BenKettlewell** [comment] 2019-07-17 21:24
> autocmd BufRead /tmp/jrnl*.txt set ft=markdown

@gregorybodnar , you sir have my sincerest thanks 💯 That worked a dream.

**Comment by gregorybodnar** [comment] 2019-07-18 02:08
Happy to help. I'm tempted to work out some syntax highlighting for time and tags as well.

**Comment by wren** [comment] 2019-07-20 20:14
@gregorybodnar Syntax highlighting would be fantastic!

I think we need to rework how the editor command is executed, so that arguments are passed properly to all editors.

PRs welcome!

**Comment by micahellison** [comment] 2020-05-16 19:15
This is duplicated by #581 but there's more conversation and a potential fix there so I'm closing this one.

**Closed by micahellison** 2020-05-16 19:15 UTC
Labels: :pushpin:, bug
