### ISSUE TITLE
Display in reverse chronological order

### ISSUE THREAD

**Issue by joshdoyle** [jrnl-org/jrnl#967] opened 2020-05-27 20:48 UTC
### Use Case/Motivation

I'd like to have the option to display jrnl entries in reverse chronological order (most recent entry first).
### Example Usage

jrnl -r would display entries in reverse chronological order.

**Comment by wren** [comment] 2020-05-27 22:16
Closing as dupe of #821. Please discuss over there.

**Closed by wren** 2020-05-27 22:16 UTC
Labels: duplicate, enhancement
