### ISSUE TITLE
[Bug Report]  AttributeError: '_PasswordRetriever' object has no attribute 'encode'

### ISSUE THREAD

**Issue by ilmanzo** [jrnl-org/jrnl#1883] opened 2024-04-16 08:06 UTC
### Diagnostic output

jrnl --diagnostic
jrnl: v4.1
Python: 3.11.8 (main, Feb 08 2024, 08:03:16) [GCC]
OS: Linux 6.8.5-1-default

### Current Behavior

```
$ jrnl                                  
Path to your journal file (leave blank for /home/andrea/.local/share/jrnl/journal.txt): /tmp/journal.txt
Do you want to encrypt your journal? (You can always change this later) [y/N] y
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Journal will be encrypted  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Do you want jrnl to use colors to display entries? (You can always change this later) [Y/n] y
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  jrnl configuration created at /home/andrea/.config/jrnl/jrnl.yaml  ┃
┃  For advanced features, read the docs at https://jrnl.sh            ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  AttributeError                                         ┃
┃  '_PasswordRetriever' object has no attribute 'encode'  ┃
┃                                                         ┃
┃  This is probably a bug. Please file an issue at:       ┃
┃  https://github.com/jrnl-org/jrnl/issues/new/choose     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

### Expected Behavior

no error message should be displayed

### Repro Steps

start a new journal instance choosing to encrypt your journal and to use colors.

### Debug output

```
$ jrnl --debug lorem ipsum
[10:00:21] DEBUG    Logging start                                                                                   main.py:32
           DEBUG    Parsed args:                                                                                    main.py:42
                    Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, template=None,              
                    on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None,                   
                    end_date=None, contains=None, strict=False, starred=False, tagged=False, limit=None,                      
                    excluded=[], edit=False, delete=False, change_time=None, export=False, tags=False, short=False,           
                    config_override=[], config_file_path='', text=['lorem', 'ipsum'], exclude_starred=False,                  
                    exclude_tagged=False)                                                                                     
           DEBUG    Reading configuration from file /home/andrea/.config/jrnl/jrnl.yaml                          install.py:91
           DEBUG    Using configuration:                                                                        install.py:117
                    "{                                                                                                        
                        'colors': {                                                                                           
                            'body': 'none',                                                                                   
                            'date': 'black',                                                                                  
                            'tags': 'yellow',                                                                                 
                            'title': 'cyan'                                                                                   
                        },                                                                                                    
                        'default_hour': 9,                                                                                    
                        'default_minute': 0,                                                                                  
                        'editor': 'nvim',                                                                                     
                        'encrypt': True,                                                                                      
                        'highlight': True,                                                                                    
                        'indent_character': '|',                                                                              
                        'journals': {'default': {'journal': '/tmp/journal.txt'}},                                             
                        'linewrap': 79,                                                                                       
                        'tagsymbols': '#@',                                                                                   
                        'template': False,                                                                                    
                        'timeformat': '%F %r',                                                                                
                        'version': 'v4.1'                                                                                     
                    }"                                                                                                        
           DEBUG    Using journal name: default                                                                  config.py:206
           DEBUG    Updating configuration with specific journal overrides:                                      config.py:111
                    {'journal': '/tmp/journal.txt'}                                                                           
           DEBUG    Scoped config:                                                                               config.py:120
                    {                                                                                                         
                        'colors': {                                                                                           
                            'body': 'none',                                                                                   
                            'date': 'black',                                                                                  
                            'tags': 'yellow',                                                                                 
                            'title': 'cyan'                                                                                   
                        },                                                                                                    
                        'default_hour': 9,                                                                                    
                        'default_minute': 0,                                                                                  
                        'editor': 'nvim',                                                                                     
                        'encrypt': True,                                                                                      
                        'highlight': True,                                                                                    
                        'indent_character': '|',                                                                              
                        'journals': {'default': {'journal': '/tmp/journal.txt'}},                                             
                        'linewrap': 79,                                                                                       
                        'tagsymbols': '#@',                                                                                   
                        'template': False,                                                                                    
                        'timeformat': '%F %r',                                                                                
                        'version': 'v4.1',                                                                                    
                        'journal': '/tmp/journal.txt'                                                                         
                    }                                                                                                         
           DEBUG    open_journal 'default'                                                                      Journal.py:473
           DEBUG    start                                                                                 BaseEncryption.py:16
           DEBUG    start                                                                         BasePasswordEncryption.py:19
           DEBUG    start                                                                               Jrnlv2Encryption.py:23
           DEBUG    decrypting                                                                    BasePasswordEncryption.py:59
  File "/usr/lib/python3.11/site-packages/jrnl/main.py", line 44, in run
    status_code = controller.run(args)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jrnl/controller.py", line 69, in run
    journal = open_journal(args.journal_name, config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jrnl/journals/Journal.py", line 513, in open_journal
    return Journal(journal_name, **config).open()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jrnl/journals/Journal.py", line 133, in open
    text = self._decrypt(text)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jrnl/journals/Journal.py", line 96, in _decrypt
    return self.encryption_method.decrypt(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jrnl/encryption/BasePasswordEncryption.py", line 64, in decrypt
    self.password = keyring_pw
    ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/jrnl/encryption/Jrnlv2Encryption.py", line 32, in password
    self._make_key()
  File "/usr/lib/python3.11/site-packages/jrnl/encryption/Jrnlv2Encryption.py", line 39, in _make_key
    password = self.password.encode(self._encoding)
               ^^^^^^^^^^^^^^^^^^^^
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/lib/python3.11/site-packages/jrnl/main.py:44 in run                                         │
│                                                                                                  │
│   43 │   │                                                                                       │
│ ❱ 44 │   │   status_code = controller.run(args)                                                  │
│   45                                                                                             │
│                                                                                                  │
│ /usr/lib/python3.11/site-packages/jrnl/controller.py:69 in run                                   │
│                                                                                                  │
│    68 │   # Get the journal we're going to be working with                                       │
│ ❱  69 │   journal = open_journal(args.journal_name, config)                                      │
│    70                                                                                            │
│                                                                                                  │
│ /usr/lib/python3.11/site-packages/jrnl/journals/Journal.py:513 in open_journal                   │
│                                                                                                  │
│   512 │   │   return LegacyJournal(journal_name, **config).open()                                │
│ ❱ 513 │   return Journal(journal_name, **config).open()                                          │
│   514                                                                                            │
│                                                                                                  │
│ /usr/lib/python3.11/site-packages/jrnl/journals/Journal.py:133 in open                           │
│                                                                                                  │
│   132 │   │   text = self._load(filename)                                                        │
│ ❱ 133 │   │   text = self._decrypt(text)                                                         │
│   134 │   │   self.entries = self._parse(text)                                                   │
│                                                                                                  │
│ /usr/lib/python3.11/site-packages/jrnl/journals/Journal.py:96 in _decrypt                        │
│                                                                                                  │
│    95 │   │                                                                                      │
│ ❱  96 │   │   return self.encryption_method.decrypt(text)                                        │
│    97                                                                                            │
│                                                                                                  │
│ /usr/lib/python3.11/site-packages/jrnl/encryption/BasePasswordEncryption.py:64 in decrypt        │
│                                                                                                  │
│   63 │   │   │   ):                                                                              │
│ ❱ 64 │   │   │   │   self.password = keyring_pw                                                  │
│   65                                                                                             │
│                                                                                                  │
│ /usr/lib/python3.11/site-packages/jrnl/encryption/Jrnlv2Encryption.py:32 in password             │
│                                                                                                  │
│   31 │   │   self._password = value                                                              │
│ ❱ 32 │   │   self._make_key()                                                                    │
│   33                                                                                             │
│                                                                                                  │
│ /usr/lib/python3.11/site-packages/jrnl/encryption/Jrnlv2Encryption.py:39 in _make_key            │
│                                                                                                  │
│   38 │   │   │   return                                                                          │
│ ❱ 39 │   │   password = self.password.encode(self._encoding)                                     │
│   40 │   │   kdf = PBKDF2HMAC(                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: '_PasswordRetriever' object has no attribute 'encode'
┏━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  AttributeError                                         ┃
┃  '_PasswordRetriever' object has no attribute 'encode'  ┃
┃                                                         ┃
┃  This is probably a bug. Please file an issue at:       ┃
┃  https://github.com/jrnl-org/jrnl/issues/new/choose     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

**Comment by micahellison** [comment] 2024-04-18 01:54
Hi @ilmanzo, thanks for the bug report. Would you mind sharing how you installed jrnl? Did you use brew, pipx, pip, etc.?

I'm not able to reproduce this issue on a WSL/Ubuntu environment with pipx:
```
$ jrnl --diagnostic
jrnl: v4.1
Python: 3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 11.4.0]
OS: Linux 5.15.146.1-microsoft-standard-WSL2
```

**Comment by ilmanzo** [comment] 2024-04-18 06:18
nevermind, it seems to only happen on the packaged version, also on 4.0.1 ; I'll close this and report at distribution bug tracker; thanks for investigating!

**Comment by malcolmlewis** [comment] 2024-05-21 13:52
@micahellison Hi, I'm the openSUSE packager/maintainer for the rpm packaged jrnl which @ilmanzo is referring to. I'm getting the same issue with version 4.1;
```bash
jrnl --diagnostic
jrnl: v4.1
Python: 3.11.9 (main, Apr 08 2024, 06:18:15) [GCC]
OS: Linux 6.8.9-1-default
```
Looking at other distribution packaging, the requires are the same, so I'm wondering if you have any thoughts on this isse?

**Comment by micahellison** [comment] 2024-05-21 14:46
Hi @malcolmlewis, thanks for the info, and for your work on maintaining the package.

It looks like it's unexpected output from [keyring](https://pypi.org/project/keyring/) on your environment. We expect a string from its `get_password` method, but instead the debug output above shows some sort of `_PasswordRetriever` object.

Could you try reproducing this in Python on your system?
```
import keyring
keyring.set_password("jrnltest", "test", "test")

# What is the type of the output? Should be <class 'str'>
type(keyring.get_password("jrnltest", "test"))

# Expecting same error: AttributeError: '_PasswordRetriever' object has no attribute 'encode'
keyring.get_password("jrnltest", "test").encode()
```
If that fails, it might be worth filing an issue on the [keyring project](https://github.com/jaraco/keyring) for help and linking back here.

**Comment by malcolmlewis** [comment] 2024-05-21 15:28
@micahellison Thanks for the fast response :smile: 
```bash
python3

Python 3.11.9 (main, Apr 08 2024, 06:18:15) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.set_password("jrnltest", "test", "test")
>>> type(keyring.get_password("jrnltest", "test"))
<class 'str'>
>>> keyring.get_password("jrnltest", "test").encode()
b'test'
>>> 
```
That appears to work fine?

**Comment by micahellison** [comment] 2024-05-22 00:25
Thanks for the test @malcolmlewis.

I'm mystified that this `_PasswordRetriever` object mentioned in the error is nowhere in jrnl's code or in keyring's code. I can't find any mention of it in the keyring issues, or any Python library at all, actually. Maybe it's something under the hood in your keyring installation, like some sort of compiled subdependency? After all, there are a variety of subdeps for various environments mentioned in [keyring's PyPI project](https://pypi.org/project/keyring/). Still, if that's the case--and your package doesn't use isolated environments like pipx--then I'd expect to see an error in that script you ran.

Maybe there's some sort of unexpected return value when the keyring isn't set. Could you try this similar script that gets a different keyring value without first setting it?
```
import keyring

type(keyring.get_password("jrnltest", "anothertest"))
keyring.get_password("jrnltest", "anothertest").encode()
```

**Comment by malcolmlewis** [comment] 2024-05-22 00:33
@micahellison That produced the error;
```bash
 python3
Python 3.11.9 (main, Apr 08 2024, 06:18:15) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> type(keyring.get_password("jrnltest", "anothertest"))
<class 'keyutils.osc._PasswordRetriever'>
>>> keyring.get_password("jrnltest", "anothertest").encode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_PasswordRetriever' object has no attribute 'encode'
```

**Comment by malcolmlewis** [comment] 2024-05-22 00:49
@micahellison @ilmanzo removing the openSUSE python311-keyring-keyutils allows password entry but doesn't seem to accept my GNOME keyring password...
<https://github.com/marcus-h/python-keyring-keyutils>

Edit: I believe it may be related to this issue by the openSUSE keyutils Maintainer <https://github.com/marcus-h/python-keyring-keyutils/issues/2>

I got the password to be accepted by seahorse by encrypting the file first....

**Comment by micahellison** [comment] 2024-05-22 14:23
Thanks for the testing and research. It's definitely the same issue as https://github.com/marcus-h/python-keyring-keyutils/issues/1 -- when no password is found in the keyring, python-keyring-keyutils returns that `_PasswordRetriever` object instead of `None` as required by keyring's backend unit tests like the issue mentions.

I'm glad we narrowed it down. I'm going to close this as won't-fix since the fix has to come from that backend, or by using a different backend, but feel free to keep discussing workarounds here.

Speaking of workarounds, if you absolutely have to use that backend, you might be able to get around it by first setting that keyring value for a particular journal with python:
```
import keyring
journal_name = "default" # Should match name in  `jrnl --list`
password = "mypassword" # Change to your journal's password
keyring.set_password("jrnl", journal_name, password)
```

**Closed as not planned by micahellison** 2024-05-22 14:23 UTC
Labels: bug, wontfix

**Comment by malcolmlewis** [comment] 2024-05-22 15:02
@micahellison yes, I noticed the test we did earlier created an entry in seahorse :wink: Thanks again for the assist in finding the root cause.
